name: C Project CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      uses: actions/setup-python@v2
      with:
        gcc-version: '11'  # Specify the GCC version you need

    - name: Run tests
      run: make test

    - name: Clean up
      run: make clean
